# Generated by Django 3.2.7 on 2021-10-10 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('date_start', models.DateTimeField(help_text='Start date should always be a Monday', null=True)),
                ('date_end', models.DateTimeField(help_text='End date should always be a Friday', null=True)),
                ('summary', djrichtextfield.models.RichTextField(help_text='Provide a quote, an image, general thoughts to describe the week.')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session_start', models.DateTimeField()),
                ('date_session_end', models.DateTimeField()),
                ('name', models.CharField(help_text='Name for this session, such as Fall 2021', max_length=255)),
                ('mentor_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(help_text='Concisely describe your challenge.', max_length=400)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishment', models.CharField(help_text='Concisely describe you accomplishment.', max_length=400)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
            ],
        ),
    ]
