# Generated by Django 3.2.8 on 2021-11-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20211010_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress_session', to='progress.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment', to='progress.progress'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='progress.progress'),
        ),
    ]
