# Generated by Django 3.2.7 on 2021-10-10 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20211010_2131'),
        ('mentorusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='mentee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentee',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentee_session', to='progress.session'),
        ),
        migrations.AlterField(
            model_name='mentorshipuser',
            name='is_mentee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mentee',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorusers.mentor'),
        ),
    ]
