# Generated by Django 3.2.7 on 2021-10-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20211010_2131'),
        ('mentorusers', '0002_auto_20211010_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentee_session', to='progress.session'),
        ),
    ]
