# Generated by Django 3.2.7 on 2021-10-10 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorusers', '0003_alter_mentee_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
